name: "default"
build: "Release"
headless: True
verbosity: 2
scene: 0 # 0 is the bistro interior, 1 is the bistro exterior, 2 is the measure_one
script:
  name: "EventCamera"
  samplesPerPixel: 1
  accumulatePass: 64 # this means 64 * 64 = 4096 spp
  russianRoulette: False
  threshold: 1.7
  needAccumulatedEvents: 100
  toleranceEvents: 4
  enableCompress: True
  enableBlockStorage : True
  directory: "64SPP_1000FPS"
  timeScale: 1000 # meas 0.1ms per frame, in the context of animation
  exitFrame: 2000 # 0 means never exit
# videoFPS: 20
# outputFile: "BistroInterior_Wine_4096spp"
