name: "default"
build: "Release"
headless: False
verbosity: 2
scene: 0 # 0 is the bistro interior, 1 is the bistro exterior, 2 is the measure_one
script:
  name: "EventCamera"
  samplesPerPixel: 8
  threshold: 1.5
  accumulateMax: 100
  exitFrame: 1000

