name: "default"
build: "Release"
headless: True
verbosity: 2
scene: 0 # 0 is the bistro interior, 1 is the bistro exterior, 2 is the measure_one
script:
  name: "EventCamera"
  samplesPerPixel: 8
  russianRoulette: True
  threshold: 1.5
  needAccumulatedEvents: 100
  toleranceEvents: 4
  enableCompress: True
  directory: "Temp"
  timeScale: 10000 # meas 0.1ms per frame, in the contect of animation
  exitFrame: 200000 # 0 means never exit
videoFPS: 60
outputFile: "BistroInterior_Wine_8spp_4tolerance"
