name: "default"
build: "Release"
headless: True
verbosity: 2
scene: 0 # 0 is the bistro interior, 1 is the bistro exterior, 2 is the measure_one
script:
  name: "EventCamera"
  samplesPerPixel: 8
  threshold: 1.5
  accumulateMax: 100
  enableCompress: True
  directory: "Temp"
  timeScale: 10000 # meas 0.1ms per frame, in the contect of animation
  exitFrame: 5000 # 0 means never exit

