name: "default"
build: "Release"
headless: True
verbosity: 2
width: 640
height: 360
script:
  name: "EventCamera"
  samplesPerPixel: 32
  accumulatePass: 64 # this means 64 * 64 = 4096 spp
  russianRoulette: False
  threshold: 1.7
  needAccumulatedEvents: 100
  toleranceEvents: 4
  enableCompress: True
  enableBlockStorage : True
  timeScale: 610
  networkTimeScale: 1000
  networkModel: "F:\\\\EventCamera\\\\config\\\\bipolar_bilif_e100.onnx"
  batchSize: 4096
